### ISSUE TITLE
vite-plus 0.2.0: native binding fails to load on Linux CI under pnpm cold install

### ISSUE THREAD

**Issue by TonyPythoneer** [voidzero-dev/vite-plus#1861]
On Linux CI, `pnpm install` of `vite-plus@0.2.0` succeeds, but the first `vp` call crashes because the platform binary is not resolvable:

```
Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828).
  cause: Error: Cannot find module '@voidzero-dev/vite-plus-linux-x64-gnu'
    cause: Error: Cannot find module './vite-plus.linux-x64-gnu.node'
```

Failed CI run: https://github.com/TonyPythoneer/jen-lab/actions/runs/27701150179

**Comment by fengmk2** [comment]
@TonyPythoneer I found the reason, cause by devEngines settings https://github.com/TonyPythoneer/jen-lab/pull/105

**Comment by JounQin** [comment]
It's broken on Cloudflare Pages (Node 20.16) now. 🥲

<img width="2794" height="506" alt="Image" src="https://github.com/user-attachments/assets/7a254a50-72b7-49cb-9caf-b5a79be3ad9d" />

**Comment by fengmk2** [comment]
@JounQin how can I reproduce it?

**Comment by 50kudos** [comment]
@JounQin Cloudflare's current build limitation is it cannot detect Node version from package.json's `engines` field.
https://developers.cloudflare.com/pages/configuration/build-image/#limitations

I faced the same issue, override node version works for me https://developers.cloudflare.com/pages/configuration/build-image/#languages-and-runtime

somehow Node 20.16 doesn't work with vite-plus 0.2.0 (and 0.2.1), 20.18 works.

**Comment by JounQin** [comment]
@50kudos I was using `.node-version` with `pnpm` previously, but I don't know why cloudflare doesn't recognize `.node-version`, and I switched to `yarn` and it works as expected. 😅
